name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Docker
      uses: actions/setup-docker@v1
    - name: Build and push Docker images
      run: |
        docker build -t user-service:latest -f user-service/Dockerfile .
        docker build -t product-service:latest -f product-service/Dockerfile .
        docker build -t order-service:latest -f order-service/Dockerfile .
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker tag user-service:latest my-registry/user-service:latest
        docker tag product-service:latest my-registry/product-service:latest
        docker tag order-service:latest my-registry/order-service:latest
        docker push my-registry/user-service:latest
        docker push my-registry/product-service:latest
        docker push my-registry/order-service:latest
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/user-service-deployment.yaml
        kubectl apply -f k8s/user-service-service.yaml
        kubectl apply -f k8s/product-service-deployment.yaml
        kubectl apply -f k8s/product-service-service.yaml
        kubectl apply -f k8s/order-service-deployment.yaml
        kubectl apply -f k8s/order-service-service.yaml
